name = "Boyz Pack"
author = "SecretJuice"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d1930a91d3bbd1e52c733f182df08a8571a22fd79304df28bd1bd3653b33616"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
