name = "Boyz Pack"
author = "SecretJuice"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "debbc039a3f5ae0be0c7c96fbdc7557a2c840fac604f0e117c94e8b637b0e5d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
