name = "Boyz Pack"
author = "SecretJuice"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0cb58a975d73f1d63e69724803c5c7d0faba98057ca380574b6ec1b40e06280"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
